### ISSUE TITLE
Return code 400 line 126

### ISSUE THREAD

**Issue by Cec343** [melissaguyre/mixpanel-segmentation-google-spreadsheets#12]
Hi @melissaguyre, I get this error from the line of code var response = UrlFetchApp.fetch(url);
Message details
Request failed for http://mixpanel.com returned code 400. Truncated server response: {"request": "/api/2.0/segmentation?api_key=**my_Mixpanel_API_key**&expire=**my_API_secret**&event=$autotrack_pageview&where=%28properties%5B%2... (use muteHttpExceptions option to examine full response) (line 126, file "Code")

Any idea what that might be?

Thank you

**Comment by matt-supermetrics** [comment]
@Cec343 have the same problem, did you work this out ever?
