### ISSUE TITLE
Why is my data all 0s?

### ISSUE THREAD

**Issue by isaacsolo** [melissaguyre/mixpanel-segmentation-google-spreadsheets#3]
Hi Melissa,
Everything runs correctly, but the data on my google sheet is all 0s. This is different than my mixpanel. Would you happen to know why?

**Comment by melissaguyre** [comment]
Is 'Asked to Login' the verbatim name of your event in Mixpanel? And if you go into Mixpanel Segmentation for that "Asked to Login" event, you are passing a property of that event called "Devices" that you are setting with the value "iPhone"? 

Basically if anything is different (the event name, the property name, the value of that property) you won't return any data. It should match up with your segmentation for the same event in Mixpanel. 

Hope this helps!
