### ISSUE TITLE
Help with authentication

### ISSUE THREAD

**Issue by jcarnicus** [melissaguyre/mixpanel-segmentation-google-spreadsheets#5]
Hi Melissa,

Looks like you're not active on here recently, but thought I'd try a shot in the dark here! I should state I'm not a developer, just an operations/product marketing type guy. But am keen to try your code here as we don't have any dev resources to help and I want to get some data out of Mixpanel into Google Sheets so I can make some tools for the sales folks. 

Looks like this  method of authentication is depreciated https://mixpanel.com/docs/api-documentation/data-export-api#auth-implementation. If you have a minute could you help me understand how this should be updated? Thanks, this will really save the day!

**Comment by matt-supermetrics** [comment]
@jcarnicus did you find a way to do this?

**Comment by jcarnicus** [comment]
@matt-supermetrics Quite a while ago, but as I recall no I didn't get this particular bit working at the time. I ended up just using Zapier or something similar, if I recall correctly. I think there are a lot more options these days.
